# Basic metadata configuration for your blog.
baseURL = "https://thmaz.github.io/"
title = "thmaz' blog"
author = "Thomas Palmen"
copyright = "Copyright © 2020, Jane Doe."
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[permalinks]
  blog = "/:filename"

[params]
  homeText = "Learning computers inside and out."