# Basic metadata configuration for your blog.
baseURL = "https://thmaz.github.io/"
title = "thmaz' blog"
author = "Thomas Palmen"
copyright = "Copyright © 2020, Jane Doe."
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[permalinks]
  blog = "/:filename"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
  homeText = "Learning computers inside and out."
  dateFormat = "Jan 2, 2006"

[taxonomies]
  tags = "tags"